# Generated by Django 5.0.4 on 2024-09-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('school_type', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=100)),
            ],
        ),
    ]
