# Generated by Django 5.0.4 on 2024-09-28 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claim', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claimedUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivedClaim', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claim',
            name='claimingUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myClaim', to=settings.AUTH_USER_MODEL),
        ),
    ]
