# Generated by Django 5.1 on 2024-08-30 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_remove_customuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='nickname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='location',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='university',
        ),
    ]
