# Generated by Django 5.1 on 2024-12-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_remove_userprofile_school_remove_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isAnonymousSchool',
            field=models.BooleanField(default=True),
        ),
    ]
