# Generated by Django 5.0.4 on 2024-09-29 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_remove_userprofile_school_remove_userprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
