# Generated by Django 5.1 on 2024-08-30 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_rename_nickname_customuser_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='name',
            new_name='nickname',
        ),
    ]
