# Generated by Django 5.0.4 on 2024-09-29 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nickname',
        ),
    ]
