# Generated by Django 5.1 on 2024-09-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_rename_class_number_userprofile_class_number_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='grades',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
