# Generated by Django 5.1 on 2024-09-04 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_userprofile_grades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='class_number_1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='class_number_2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='class_number_3',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='class_number_4',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='class_number_5',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='class_number_6',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='grade_1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='grade_2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='grade_3',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='grade_4',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='grade_5',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='grade_6',
        ),
    ]
