# Generated by Django 5.1 on 2024-09-03 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_alter_comment_user'),
        ('classboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classboard',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.school'),
        ),
        migrations.AlterField(
            model_name='classboard',
            name='class_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='classboard',
            name='grade',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
