# Generated by Django 5.1 on 2024-09-03 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classboard', '0002_alter_classboard_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('school_type', models.CharField(max_length=100)),
                ('school_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='classboard',
            name='class_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='classboard',
            name='grade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='classboard',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classboard.school'),
        ),
    ]
