# Generated by Django 5.1 on 2024-09-03 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classboard', '0003_school_alter_classboard_class_number_and_more'),
        ('member', '0008_userprofile_grades'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='classboard',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classboards', to='member.school'),
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='board',
            new_name='class_board',
        ),
        migrations.RemoveField(
            model_name='classboard',
            name='class_number',
        ),
        migrations.RemoveField(
            model_name='classboard',
            name='grade',
        ),
        migrations.AlterField(
            model_name='classboard',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
