# Generated by Django 5.1 on 2024-10-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classboard', '0003_alter_classboard_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classboard',
            name='class_number',
        ),
        migrations.AddField(
            model_name='classboard',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
