# Generated by Django 5.1 on 2024-09-03 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classboard', '0004_alter_classboard_school_and_more'),
        ('member', '0008_userprofile_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classboard',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classboards', to='member.school'),
        ),
    ]
