# Generated by Django 5.1 on 2024-09-03 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classboard', '0005_alter_classboard_school'),
        ('member', '0008_userprofile_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='classboard',
            name='class_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classboard',
            name='grade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='classboard',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='member.school'),
        ),
    ]
