# Generated by Django 5.1 on 2024-08-30 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='body',
            field=models.TextField(default='default'),
        ),
    ]
