# Generated by Django 5.0.4 on 2024-09-29 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
    ]
