# Generated by Django 5.1 on 2024-09-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_rename_date_board_created_at_alter_board_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('school_type', models.CharField(max_length=255)),
            ],
        ),
    ]
