# Generated by Django 5.1 on 2024-09-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_board_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='province',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='school',
            name='name',
        ),
        migrations.AddField(
            model_name='school',
            name='school_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(max_length=100),
        ),
    ]
