# Generated by Django 5.1 on 2024-09-03 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_rename_province_school_city_remove_school_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.school'),
        ),
    ]
