# Generated by Django 5.1 on 2024-09-04 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='school',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
