# Generated by Django 5.1 on 2024-09-04 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_board_school'),
        ('member', '0009_remove_userprofile_class_number_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.school'),
        ),
    ]
