# Generated by Django 5.1 on 2024-09-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_board_admission_year_alter_board_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='admission_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
